name: CI for Autotools

on:
  push:
    paths-ignore:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "**.cmake.in"
      - "cmake/**"
      - "CMake*"
      - ".github/workflows/ci_cmake.yml"
  pull_request:

jobs:

  linux-multi1:
    runs-on: ubuntu-latest
    name: Build 1 on Linux
    steps:

    - name: Install system dependencies
      run: |
        sudo apt-get update -yq
        sudo apt-get install -yq --no-install-recommends \
            zlib1g-dev libmpich-dev mpich

    - name: Checkout source code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Run bootstrap script
      run: ./bootstrap

    - name: Make check with debug, without shared
      shell: bash
      run: |
        DIR="checkdebug_static" && mkdir -p "$DIR" && cd "$DIR"
        ../configure --disable-shared --enable-debug \
            CFLAGS="-O0 -g -Wall"
        make -j V=0
        make -j check V=0
        cd ..

    - name: Make check with MPI and debug
      shell: bash
      run: |
        DIR="checkMPIdebug" && mkdir -p "$DIR" && cd "$DIR"
        ../configure --enable-mpi --enable-debug \
            CFLAGS="-O0 -g -Wall"
        make -j V=0
        make -j check V=0
        cd ..

    - name: Make check with MPI, without debug
      shell: bash
      run: |
        DIR="checkMPI" && mkdir -p "$DIR" && cd "$DIR"
        ../configure --enable-mpi \
            CFLAGS="-O2"
        make -j V=0
        make -j check V=0
        cd ..

    - name: Upload log files
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: linux_multi1_log
        path: |
          ./**/test-suite.log
          ./**/config.log

  linux-multi2:
    runs-on: ubuntu-latest
    name: Build 2 on Linux
    steps:

    - name: Install system dependencies
      run: |
        sudo apt-get update -yq
        sudo apt-get install -yq --no-install-recommends \
            zlib1g-dev libmpich-dev mpich

    - name: Checkout source code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Run bootstrap script
      run: ./bootstrap

    - name: Make check with MPI, debug and C++ compiler
      shell: bash
      run: |
        DIR="checkMPIdebugCXX" && mkdir -p "$DIR" && cd "$DIR"
        ../configure --enable-mpi --enable-debug \
            CFLAGS="-O0" CC=mpicxx
        make -j V=0
        make -j check V=0
        cd ..

    - name: Make distcheck without MPI and debug
      shell: bash
      run: |
        DIR="distcheck" && mkdir -p "$DIR" && cd "$DIR"
        ../configure
        make -j distcheck V=0
        cd ..

    - name: Upload log files
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: linux_multi2_log
        path: |
          ./**/test-suite.log
          ./**/config.log

  linux-install:
    runs-on: ubuntu-latest
    name: Make install on Linux
    steps:

    - name: Install system dependencies
      run: |
        sudo apt-get update -yq
        sudo apt-get install -yq --no-install-recommends \
            zlib1g-dev libmpich-dev mpich

    - name: Checkout source code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Fix libsc to version 547a38ccd081c3e12a7ee43478a14638fb516133
      shell: bash
      run: (cd sc && git fetch --tags && git checkout 547a38ccd081c3e12a7ee43478a14638fb516133)
    - name: Run bootstrap script
      run: ./bootstrap

    - name: Install libsc with debug, without shared
      shell: bash
      run: |
        DIR="sc-checkdebug_static" && mkdir -p "$DIR" && cd "$DIR"
        ../sc/configure --disable-shared --enable-debug \
            CFLAGS="-O0 -g -Wall -pedantic"
        make -j V=0
        make -j check V=0
        make -j install V=0
        cd ..
        rm -rf sc/

    - name: Install p4est with debug, without shared
      shell: bash
      run: |
        DIR="p4est-checkdebug_static" && mkdir -p "$DIR" && cd "$DIR"
        ../configure --disable-shared --enable-debug \
            --with-sc="$PWD/../sc-checkdebug_static/local" \
            CFLAGS="-O0 -g -Wall -pedantic"
        make -j V=0
        make -j check V=0
        make -j install V=0
        cd ..

  linux-tarball:
    runs-on: ubuntu-latest
    name: Pack tarball on Linux
    steps:

    - name: Install system dependencies
      run: |
        sudo apt-get update -yq
        sudo apt-get install -yq --no-install-recommends \
            zlib1g-dev libmpich-dev mpich

    - name: Checkout source code
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    - name: Identify version
      shell: bash
      run: |
        git tag
        git describe --abbrev=4 --match 'v*'

    - name: Run bootstrap script
      run: ./bootstrap

    - name: Configure and make
      shell: bash
      run: |
        DIR="tarball" && mkdir -p "$DIR" && cd "$DIR"
        ../configure --enable-mpi --enable-debug \
            CFLAGS="-O0 -g -pedantic -Wall -Wextra -Werror -Wno-unused-parameter \
                    -Wno-builtin-declaration-mismatch -Wno-implicit-fallthrough"
        make -j V=0
        make -j check V=0
        make -j distcheck V=0
        mv p4est-*.tar.gz ..
        cd ..

    - name: Upload tarball
      uses: actions/upload-artifact@v2
      with:
        name: p4est_tarball
        path: ./p4est-*.tar.gz
